on:
  push:
    paths:
      - 'version/tg2link.txt'

name: tg2link
jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2.4.0
      
      - name: Setup variables
        run: |
          echo "VERSION=$(cat "version/tg2link.txt" | head -1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Get Dockerfile
        run: |
          cp src/tg2link/* $PWD

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1.14.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build latest
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/tg2link:latest
            ${{ secrets.DOCKER_USERNAME }}/tg2link:${{ env.VERSION }}
