on:
  push:
    paths:
      - 'version/xray'

name: xray
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Env
        run: |
          echo "GOLANG=$(wget -qO- https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep 'version' | cut -d\" -f4 | head -1)" >> $GITHUB_ENV
          echo "VERSION=$(cat "version/xray" | head -n1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Install Golang
        uses: actions/checkout@v5
        with: 
          go-version: ${{ env.GOLANG }}

      - name: Start build
        run: |
          cp src/build/xray.sh $PWD/xray.sh && chmod +x xray.sh && ./xray.sh

      - name: Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          draft: false
          prerelease: false
          allowUpdates: true
          artifacts: |
            ./release/*

  push:
    needs: build
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "VERSION=$(cat "version/xray" | head -1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Get Dockerfile
        run: |
          cp src/xray/* $PWD

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build latest
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/xray:latest
            ${{ secrets.DOCKER_USERNAME }}/xray:${{ env.VERSION }}

  test:
    needs: [build,push]
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "VERSION=$(cat "version/xray" | head -1 | tr -d [:space:])" >> $GITHUB_ENV
        shell: bash

      - name: Test Docker image
        run: |
          docker run --rm --entrypoint /usr/bin/xray ${{ secrets.DOCKER_USERNAME }}/xray:latest -version
          docker run --rm --entrypoint /usr/bin/xray ${{ secrets.DOCKER_USERNAME }}/xray:${{ env.VERSION }} -version